//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MVC_APTA_CMS_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apta_admin
    {
        public apta_admin()
        {
            this.conference_event = new HashSet<conference_event>();
        }
    
        public int adminID { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Phone { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Password { get; set; }
    
        public virtual ICollection<conference_event> conference_event { get; set; }
    }
}
